CREATE TABLE BOOK(
	ID INT AUTO_INCREMENT,
	ISBN VARCHAR(255),
	TITLE VARCHAR(255),
	AUTHOR VARCHAR(255),
	PUBLISHER VARCHAR(255),
	COUNTRY VARCHAR(255)
);

CREATE TABLE REVIEW(
	ID INT AUTO_INCREMENT,
	CONTENT VARCHAR(255)
);

CREATE TABLE USER(
	ID INT AUTO_INCREMENT,
	USER_NAME VARCHAR(255),
	PASSWORD VARCHAR(255)
);